### ISSUE TITLE
TaskManager is not implemented in DelfiPQCore

### ISSUE THREAD

**Issue by CasperBroekhuizen** [DelfiSpace/DelfiPQcore#1]
DelfiPQCore has it's own implementation of the TaskManager, thus the TaskManager is not implemented in DelfiPQCore.

The TaskManager however does not initialize the Tasks.

Right now the TaskManager object might either be redundant or deprecated.

**Comment by StefanoSperetta** [comment]
Fixed in beb2f86ea8241dcf83364e070fcd2e62ceb31bd2
