### ISSUE TITLE
Every Module can only have 1 PeriodicTask.

### ISSUE THREAD

**Issue by CasperBroekhuizen** [DelfiSpace/DelfiPQcore#16]
The PeriodicTask currently occupies one of the Timers (TIMER32_0_BASE) to notify itself.
So when a second periodicTask is created, it will take that timer and assign it to itself. (deregistering the first PeriodicTask). 

Possible solution is to have a separate interrupt handler that holds a list of periodic tasks to notify all of them, instead of having the PeriodicTask notify itself.

**Comment by StefanoSperetta** [comment]
Related to https://github.com/DelfiSpace/DelfiPQcore/issues/7

**Comment by CasperBroekhuizen** [comment]
Fixed in https://github.com/DelfiSpace/DelfiPQcore/commit/a22cd21b9745ee0a66960cfa21dc470674c77c20 , By adding a PeriodicTaskNotifier.
