### ISSUE TITLE
Print at startup the status of the oscillators

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#18]
I would like to print at startup the status of the different oscillators (right now only HF and LF but shortly also the DCO with external resistor), exactly as it is done by the reset handler. I would want this to happen by default in all projects so we can monitor on the console if one oscillator is not working...

How to do it? Might be a good idea to have a simple function inside DelfiPQCore that just prints the status? Querying the status is already implemented by getHFOscillatorStatus() and getLFOscillatorStatus(). 

Any idea?

**Comment by CasperBroekhuizen** [comment]
Since you want to print it, it should be called after the initialization of the serial port.
I think the easiest right now is to absorb the functionality in the resethandler as well

**Comment by CasperBroekhuizen** [comment]
Besides InterruptStatusRegister (which holds the Fault Flags), there's also the StatusRegister which holds the status of all the clocks (on/off, ready/not ready). Obtaining them all will lead to a bootup log like this:
![image](https://user-images.githubusercontent.com/17972261/73839428-41e18300-4816-11ea-87a8-d76f01c389b1.png)

Should we ommit clock status? or maybe only print if on.
I assume the CS Fault Status will be saved on FRAM/Telemetry, but should the regular clock status also be saved on FRAM or Telemetry?

**Comment by StefanoSperetta** [comment]
As stated verbally, all clocks status might be a bit too much but errors are needed indeed.

We might have to think about a proper place to put the code though...

**Comment by CasperBroekhuizen** [comment]
Reduced the clock status print in https://github.com/DelfiSpace/DelfiPQcore/commit/74e4eb8a4bebc98e1b97167a8a2fa55ed68a7f75 . 

Currently still in ResetService. We discussed to collect all fault-collection to a central object. Maybe a good place is the bootloader as it is always present in SLOT0 and always loaded. and the reset-faults should be used in the bootloader policies (https://github.com/DelfiSpace/DelfiPQcore/issues/21)

**Comment by CasperBroekhuizen** [comment]
Absorbed in HWMonitor
