### ISSUE TITLE
Software update metadata packets not numbered

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#19]

**Comment by CasperBroekhuizen** [comment]
CRCs are not numbered, thus not checking wether the correct CRC is loaded as the receiver expects them in order.

https://github.com/DelfiSpace/DelfiPQcore/commit/3f8d8a460a4514d2c7b4edf08b2ddb42969fadc7
- Added numbers to CRC, so CRC can be retransmitted and the missing CRCs can be requested.
- Missing blocks/CRCs are now returned when the update is active
