### ISSUE TITLE
Command handler is not sending correct error response in some cases

### ISSUE THREAD

**Issue by MFvandenBos** [DelfiSpace/DelfiPQcore#2]
While testing comms: 

I was sending: 
{"_send_":"SendRaw","dest":"4","src":"1","data":"78 1"}

The micro controller does not seem to respond to this. This also happens for these services: 
(service 0 and 18 are both existing services that are not fully implemented I think may need an issue for those as well since it is not a fault of command handler ) 

java.lang.AssertionError: No response from board 4 on commmand: 0
No response from board 4 on commmand: 18
No response from board 4 on commmand: 57
No response from board 4 on commmand: 78
No response from board 4 on commmand: 124
No response from board 4 on commmand: 161
No response from board 4 on commmand: 176

While testing EPS, similar issue but then for services: 

java.lang.AssertionError: No response from board 2 on commmand: 0
No response from board 2 on commmand: 18
No response from board 2 on commmand: 44
No response from board 2 on commmand: 124
No response from board 2 on commmand: 165

**Comment by StefanoSperetta** [comment]
Old error, the system has been significantly changed since then. Closing as superseded by events.
