### ISSUE TITLE
Software update: figure out a policy for booting

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#21]
Currently, we have only 2 cases: boot once or boot permanently. Is there a more fault-tolerant way? More options?

**Comment by CasperBroekhuizen** [comment]
"boot-once" was not fault tolerant if the target slot has a piece of broken software, and would get stuck in a boot-loop. Fixed in commit https://github.com/DelfiSpace/DelfiPQcore/commit/6a7ca94fdf4976c88639a46dbafff9232bebebdc , by resetting the target_slot _before_ doing the 'jump'
