### ISSUE TITLE
SoftwareUpdate: Add failure of FRAM to bootloader

### ISSUE THREAD

**Issue by CasperBroekhuizen** [DelfiSpace/DelfiPQcore#26]
FRAM needs to be available for bootloader. 
Add fallback if it's not available (either not on board or stopped working).

related to https://github.com/DelfiSpace/DelfiPQcore/issues/25

**Comment by CasperBroekhuizen** [comment]
Added a FRAM->ping in https://github.com/DelfiSpace/DelfiPQcore/commit/bb94cfcd0eb6ec10c1dfe3ac5802b40d39ffb66e

**Comment by StefanoSperetta** [comment]
What happens in case the FRAM is not available?

I see the log message being sent but I do not understand exactly what are the consequences, system-wise.

**Comment by CasperBroekhuizen** [comment]
No target-slot can be realised from the FRAM. The bootloader 'skips' the jump functionality so a regular boot in SLOT0 will be resumed.

Meaning, if the FRAM breaks, the system will fallback onto Slot0. If the FRAM is permanently broken, the system can also not perform any reprogramming.

**Comment by StefanoSperetta** [comment]
Great! 

If we switch to some kind of error correction system on the FRAM, we can also clean the FRAM and re-initialize it with default data. But in the future...

**Comment by StefanoSperetta** [comment]
This issue seems more or less solved by now, with the ping() function being called. We might argue the ping() is not a super-secure method but for now, it has to stay like this.

In the future, we can think about adding error correction (we might add an issue but I would put it for software v2)...
