### ISSUE TITLE
Readout MCU temperature

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#27]
The MSP can use the ADC to readout the MCU temperature. There is also a calibration table which is holding device-specific parameters.

**Comment by CasperBroekhuizen** [comment]
I am assuming this is according to the example code provided on the resource explorer?
http://dev.ti.com/tirex/explore/node?node=AHKzWRRAPjba2EbmE6owSg__z-lQYNj__LATEST

Also, I think this could be implemented in the HWMonitor object (issue https://github.com/DelfiSpace/DelfiPQcore/issues/24)?

**Comment by CasperBroekhuizen** [comment]
https://github.com/DelfiSpace/DelfiPQcore/commits/HWMonitor implements a readMCUTemp function, which will get a result using the ADC14 Module, this result can be accessed using getMCUTemp()

The EPS Has a HWMonitor branch to test functionality.
https://github.com/DelfiSpace/EPS_FlightSoftware/tree/HWMonitor

**Comment by StefanoSperetta** [comment]
This looks working rather well. @Sevket: did we see discrepancy during the solar panel tests? Otherwise, I think we can close this.

**Comment by StefanoSperetta** [comment]
Seems like the temperature is within 2degC of the battery and solar panel temperature, so I consider it correct.

Closing the issue...
