### ISSUE TITLE
TaskManager accessing private members of Task

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#3]
The Task class has been changed a little and the scheduling mechanism (method executeTask) is public to be accessed by TaskManager. This might be risky as people might want to override executeTask. This could be solved by making executeTask private and making TaskManager a friend class of Task (see example https://www.geeksforgeeks.org/friend-class-function-cpp/).

Otherwise, the TaskManager::start() function might be turned into a static member of the Task method (capable of accessing its own private method).

Opinions @CasperBroekhuizen?

**Comment by CasperBroekhuizen** [comment]
Overriding the executeTask when implementing a Task is indeed behaviour I've been wanting to implement. For example, a task always de-notifies itself after execution, thus when implementing a continuous task that is run on every cycle needs some external trigger to kick the task making it a serious pain to implement, overriding the executeTask function to get rid of this de-notify is however a much more elegant solution. However another consideration is that if the executeTask may be overridden, you can also make it a virtual method and require one to override it when implementing a task and get rid of the lambda function structure.

Making the execute public might allow tasks to run other tasks, which could be intended behaviour. However the risks I think you mean is unintended recursion or bricking the task-execution, basically locking up the task execution. However, this behaviour is also not protected from in the current model, giving the task a lambda function that gets in an infinite loop will break the system in a similar way.

**Comment by StefanoSperetta** [comment]
The notify() function handles the task weak up and cannot be overridden anymore.
The notified() function can be overridden for special needs.
The executeTask() function has been made private and accessed by TaskManager. The function cannot be overridden anymore.

The issue has been solved in https://github.com/DelfiSpace/DelfiPQcore/commit/e9e3d60424976083ca0143bab32d58586087d55b
