### ISSUE TITLE
Serial Console will never print if RXD pin is faulty

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#38]
If the MCU RXD pin (or the programmer connector) is not properly soldered (but only on pin 4), the serial port will never print a message despite all connections are correct (except the RXD, due to the serial port disable mechanism).

It might have saved me 2 hours if we would always print something on the console (even if the isEnabled() function returns false). Even a stupid message when the board powers up saying, if isEnabled() == false, "error serial port not connected". If we see that message, then we have a problem... otherwise, if the cable is not connected, we will never see it.

I pushed a possible solution (e775ce0198baddedbd76816bc29d9358abbd9fe5). What do you think?

**Comment by CasperBroekhuizen** [comment]
Yes i like that, also that its printed automatically during init 👍
