### ISSUE TITLE
Create a generic command handler and data transfer unit

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DelfiPQcore#5]
Currently, PQ9Frame is part of PQ9Bus. This seems natural but forces DelfiPQcore (and in particular CommandHandler) to depend on PQ9Bus.

It does not seem too nice (but not really a problem) but it also creates another problem: the command handler can only be directly connected to a PQ9Bus instance (used as a slave). This would not be the case in the OBC (being the PQ9 bus master) as OBC should extract its commands FROM a PQ9Frame (and so not being directly connected to a PQ9Bus). This is also the case on the HPI, where PQ9Frames come over an RS485 bus (and thus via RS485 class, not PQ9Bus).

For HPI, this was hacked by copying CommandHandler (too in a rush to think about a nice solution) into the HPI project and modifying it to handle an RS485 instance.

Possible solutions could be:
- creating a parent class (parent of PQ9Bus and RS485) but this might create a circular dependency between PQ9Bus and DelfiPQcore projects
- using Lambdas (might be best to test this approach after switching to CCS 9.3 that should potentially solve the lambda debug issue)

Opinions, @CasperBroekhuizen ?

**Comment by CasperBroekhuizen** [comment]
I agree with the problem that PQ9Core (mostly CommandHandler) very much forces the user to use the PQ9Bus. I agree that both possible solutions you give are quite nice. However personally I'm more in favor of creating a parent-class.

I think to create an abstract (or interface) base class that holds a template for a communication protocol/method might be quite nice. (similar to how PQ9Sender is)
This would also require an abstract or interface base class for a communication frame, as the commandHandler copies from receive buffers.

After that the CommandHandler/Services in the PQ9Core can be made much more general.
However, depencies on PQ9Frame will probably continue to exist in the PQCore, as the services are require to interpret data received.

**Comment by CasperBroekhuizen** [comment]
Making both the RS485Bus and PQ9Bus inherit from a generic bus (virtual class) is in my opinion the optimal scenario. The structure of this base-class can be:

![bus_base](https://user-images.githubusercontent.com/17972261/72259556-143b5c80-3611-11ea-8604-a11e63b0f49a.png)

Currently PQ9Sender is such a baseclass, however it can be extended to more virtual functions, and maybe consider being renamed.

One can also consider making PQ9Frame inherit from a generic Frame, if a different protocol structure might be required in the future.

**Comment by StefanoSperetta** [comment]
Agreed, you need the PQ9Frame to inherit from a base class anyway if you want a generic bus interface.
I would not inherit the constructor nor the begin function to leave freedom in initializing the bus. Fundamental functions are the transmit (probably send might be a better name), receptionHandler registration and the getAddress.

**Comment by CasperBroekhuizen** [comment]
Base class of the Bus is now called DataBus and is a slightly more extended baseclass then PQ9Sender. The DataBus resides in the DelfiPQCore (https://github.com/DelfiSpace/DelfiPQcore/commit/6c49cc57f15b9f027fdeaaac86c81d8b0d9efe3d)

Busses use now new Baseclass:
- https://github.com/DelfiSpace/PQ9Bus/commit/844dadeeb632760b81043a405d8547136d7e132a
- https://github.com/DelfiSpace/HPI_FlightSoftware/commit/870cda9412bed78f61d55a6a45b09b0b3c3e7710 

Todo: 
- PQ9Sender should be renamed almost everywhere
- The CommandHandler and Services should be generalized to depend not on the PQ9Frame specifics but on a general DataFrame.

**Comment by CasperBroekhuizen** [comment]
Renamed PQ9Sender in services for now (https://github.com/DelfiSpace/FlightSoftwareWorkspace/commit/5341f908d7a027ba85c60070e1513325d9e3cfe2)

**Comment by CasperBroekhuizen** [comment]
PQ9Frame now extends baseclass DataFrame, which is used in all of the services. The commandHandler has been turned into a Template Class in order to handle different communications frame later and to not be dependent anymore on the PQ9Bus library.
https://github.com/DelfiSpace/DelfiPQcore/commit/d68ee6f83c1c135ce324a6a5420feb4de45c8efe
https://github.com/DelfiSpace/PQ9Bus/commit/53de7073e1390eefe0185fe9f7de93f2fbfd04e6

All other services should now use DataFrame instead of PQ9Frame and initialization of the CommandHandler should have a Template designation: (e.g. CommandHandler<PQ9Frame> )

**Comment by CasperBroekhuizen** [comment]
Added split of layers in https://github.com/DelfiSpace/DelfiPQcore/commit/a22cd21b9745ee0a66960cfa21dc470674c77c20

and template of commandhandler in
https://github.com/DelfiSpace/DelfiPQcore/commit/d68ee6f83c1c135ce324a6a5420feb4de45c8efe
